name: bouso
favicon: null
layout_spectrum: 0.13379584695212543
typography_spectrum: 0.37995106633752584
title: Michael Bouso
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4243877346161753
  lightness: 0.6298013278283179
  saturation: 0.25316294375807047
  rhythmicContrast: 0.6222797215450555
purpose: []
